"""create_asset_data_table

Revision ID: 1213bfab74f0
Revises: 19fd0b071750
Create Date: 2026-01-24 18:23:33.373877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1213bfab74f0'
down_revision: Union[str, Sequence[str], None] = '19fd0b071750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_data',
    sa.Column('asset_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('expected_return', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('volatility', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('correlation_matrix', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('asset_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_data')
    # ### end Alembic commands ###
