"""add user_id to SimulationResult

Revision ID: 533269cf7904
Revises: efa4648a057f
Create Date: 2026-02-22 21:59:21.150655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533269cf7904'
down_revision: Union[str, Sequence[str], None] = 'efa4648a057f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_results', sa.Column('user_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_results', 'user_id')
    # ### end Alembic commands ###

