"""add affiliate_brokers table

Revision ID: d6eecacb1b7f
Revises: ad8df69b806b
Create Date: 2026-03-26 00:05:32.496075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.database import GUID

# revision identifiers, used by Alembic.
revision: str = 'd6eecacb1b7f'
down_revision: Union[str, Sequence[str], None] = 'ad8df69b806b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('description', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('affiliate_url', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_brokers_id'), 'affiliate_brokers', ['id'], unique=False)

    # Check if column already exists to avoid errors during re-run
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('asset_data')]
    if 'dividend_yield' not in columns:
        op.add_column('asset_data', sa.Column('dividend_yield', sa.DECIMAL(precision=8, scale=6), nullable=True))

    # Type change for user_id (only for Postgres as SQLite doesn't support it easily)
    if bind.dialect.name == 'postgresql':
        op.execute('ALTER TABLE simulation_results ALTER COLUMN user_id TYPE UUID USING user_id::UUID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('ALTER TABLE simulation_results ALTER COLUMN user_id TYPE VARCHAR(36)')

    op.drop_column('asset_data', 'dividend_yield')
    op.drop_index(op.f('ix_affiliate_brokers_id'), table_name='affiliate_brokers')
    op.drop_table('affiliate_brokers')
    # ### end Alembic commands ###

