"""Add historical_prices to AssetData

Revision ID: efa4648a057f
Revises: fb089c96a6d9
Create Date: 2026-02-12 22:24:02.666856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa4648a057f'
down_revision: Union[str, Sequence[str], None] = 'fb089c96a6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_data', sa.Column('historical_prices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_data', 'historical_prices')
    # ### end Alembic commands ###
